"use client"

/**
 * The study surface's session state, shared by both producers.
 *
 * Pause is the study surface (plans/product-vision.md, 2026-08-20 #4), and what
 * it studies outlives any one pause: a question asked two holds ago is still
 * part of this session's thread, and the review material is regenerated by the
 * worker as the conversation earns new material — it must not restart from a
 * shimmer every time the overlay unmounts on a resume. So both live here, in
 * the producer, for exactly as long as the session does.
 *
 * The hook is backend-agnostic on purpose: the live adapter hands it RPCs and
 * the mock hands it canned answers, and the overlay cannot tell them apart —
 * the same split that makes the design playground a real test of the surface.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react"

import type {
  AskExchange,
  ReviewState,
  StudySession,
  StudyTab,
} from "./contract"
import {
  ASK_HISTORY_MESSAGES,
  REVIEW_FALLBACK_POLL_MS,
  REVIEW_MAX_POLLS,
  REVIEW_POLL_MS,
  type AskMessage,
  type AskResponse,
  type ReviewMaterial,
  type ReviewResponse,
} from "./protocol"

/**
 * What a producer must supply. Both methods are one round trip: the polling,
 * the thread, and the cache are this hook's business, so a producer only has to
 * know how to reach its answerer.
 */
export interface StudyBackend {
  ask: (
    question: string,
    turnId: string | null,
    history: AskMessage[]
  ) => Promise<AskResponse>
  review: () => Promise<ReviewResponse>
}

export interface Study extends StudySession {
  /**
   * Clears the thread, the tab and the cached material. Called when the room
   * goes away: the next session studies its own conversation, not this one's.
   */
  reset: () => void
}

/** What the producer knows and the study surface renders. */
export interface StudyOptions {
  /**
   * Told about every question as it is asked, so the live producer can put this
   * hold's questions on the resume payload without the overlay knowing that the
   * pause pipeline exists. Must be referentially stable.
   */
  onAsk?: (question: string) => void
  /**
   * The worker's `tutor.review_version`, or null where nobody publishes one
   * (replay, a worker from before step 3). Every change to this is the worker
   * saying "there is new material" — which is the whole of Review's push.
   */
  reviewVersion?: number | null
  /** The confirmed goal, one line, from `tutor.goal`. Null until it exists. */
  goal?: string | null
}

const NO_REVIEW_STATE: ReviewState = {
  material: null,
  loading: false,
  absent: false,
  version: null,
  updatedAt: null,
}

export function useStudy(
  backend: StudyBackend,
  { onAsk, reviewVersion = null, goal = null }: StudyOptions = {}
): Study {
  const [thread, setThread] = useState<AskExchange[]>([])
  const [tab, setTab] = useState<StudyTab>("transcript")

  const [review, setReview] = useState<ReviewState>(NO_REVIEW_STATE)
  /**
   * Whether the learner has ever opened the tab. Review costs the worker a
   * model call, so nothing is fetched for a session where nobody looked — but
   * once they HAVE looked, the tab stays current whether or not it is on
   * screen, because the next hold should open onto today's material rather
   * than onto a shimmer.
   */
  const [reviewOpened, setReviewOpened] = useState(false)
  /**
   * What the tab is currently showing, read by the fetch loop without making
   * it depend on the render that produced it. `version` is the snapshot that
   * material came from; null means the worker never named one.
   */
  const held = useRef<{
    material: ReviewMaterial
    version: number | null
  } | null>(null)

  /** Monotonic within a session; ids only have to be unique among siblings. */
  const asked = useRef(0)

  /**
   * The thread, mirrored so that `ask` can read it (for the history it sends)
   * and patch it (when the answer lands) without either depending on the render
   * that produced it.
   */
  const threadRef = useRef<AskExchange[]>([])
  const update = useCallback(
    (patch: (prev: readonly AskExchange[]) => AskExchange[]) => {
      threadRef.current = patch(threadRef.current)
      setThread(threadRef.current)
    },
    []
  )

  const ask = useCallback(
    (question: string, turnId: string | null) => {
      const trimmed = question.trim()
      if (!trimmed) return
      const id = `ask-${(asked.current += 1)}`
      const history = historyFrom(threadRef.current)
      update((prev) => [
        ...prev,
        { id, question: trimmed, answer: null, turnId },
      ])
      onAsk?.(trimmed)

      backend
        .ask(trimmed, turnId, history)
        .then((response) => {
          // An `error` with no answer is the only failure the worker reports;
          // hitting the invisible cap is not one — it comes back as a real
          // answer with `limit`, and renders like any other.
          update((prev) =>
            prev.map((entry) =>
              entry.id === id
                ? response.answer
                  ? {
                      ...entry,
                      answer: response.answer,
                      limit: response.limit === true,
                    }
                  : { ...entry, failed: true }
                : entry
            )
          )
        })
        .catch(() => {
          update((prev) =>
            prev.map((entry) =>
              entry.id === id ? { ...entry, failed: true } : entry
            )
          )
        })
    },
    [backend, onAsk, update]
  )

  /** Opening the tab is what asks for material the first time. */
  const changeTab = useCallback((next: StudyTab) => {
    setTab(next)
    if (next === "review") setReviewOpened(true)
  }, [])

  /**
   * REVIEW IS PUSHED, NOT POLLED.
   *
   * The worker regenerates this session's material as the conversation gives it
   * something new to say and bumps `tutor.review_version`; a change to that
   * attribute re-runs this effect, which fetches once and swaps the material
   * under whatever is on screen. What is already there stays there until the
   * new snapshot actually arrives — a learner mid-sentence must never watch the
   * page they are reading turn into a shimmer.
   *
   * Polling survives only as a fallback, and only for the two cases the push
   * cannot cover: material that has never arrived at all (the worker is still
   * generating the first snapshot, so the fast `REVIEW_POLL_MS` loop rides that
   * out and then drops to `REVIEW_FALLBACK_POLL_MS` indefinitely), and a reply
   * that carries no version, which is what a worker from before this contract
   * looks like. A ready reply WITH a version stops the loop dead: from then on
   * the attribute is the only thing that asks for anything.
   */
  useEffect(() => {
    if (!reviewOpened) return

    const current = held.current
    // Up to date: we have material, and either nobody publishes versions (the
    // fallback loop below owns that case) or ours is the version being
    // advertised. Re-running for an unchanged attribute buys a model call.
    if (
      current !== null &&
      current.version !== null &&
      reviewVersion !== null &&
      current.version >= reviewVersion
    ) {
      return
    }

    let cancelled = false
    let timer: ReturnType<typeof setTimeout> | undefined

    // The shimmer is only for a tab with nothing on it. A refresh behind
    // existing material is silent until it lands.
    if (current === null) {
      setReview((prev) => ({ ...prev, loading: true, absent: false }))
    }

    const attempt = async (tries: number) => {
      let response: ReviewResponse | null = null
      try {
        response = await backend.review()
      } catch {
        // A transport failure and a "not ready" carry the same instruction:
        // ask again later. Neither is worth telling the learner about.
        response = null
      }
      if (cancelled) return

      if (response?.ready) {
        const version =
          typeof response.version === "number" ? response.version : null
        const replaced = held.current !== null
        const material: ReviewMaterial = {
          vocab: response.vocab ?? [],
          phrases: response.phrases ?? [],
          tables: response.tables ?? [],
        }
        held.current = { material, version }
        setReview({
          material,
          loading: false,
          absent: false,
          version,
          // Only when it REPLACED something. The first material to arrive is
          // not an update, it is the material.
          updatedAt: replaced ? Date.now() : null,
        })
        // A version means the attribute will tell us about the next one.
        if (version === null) {
          timer = setTimeout(() => void attempt(0), REVIEW_FALLBACK_POLL_MS)
        }
        return
      }

      const fast = tries + 1 < REVIEW_MAX_POLLS
      // Half a minute of asking is well past any honest generation; say so,
      // and keep a slow watch in case the worker is simply late.
      if (!fast && held.current === null) {
        setReview((prev) => ({ ...prev, loading: false, absent: true }))
      }
      timer = setTimeout(
        () => void attempt(tries + 1),
        fast ? REVIEW_POLL_MS : REVIEW_FALLBACK_POLL_MS
      )
    }

    void attempt(0)
    return () => {
      cancelled = true
      if (timer !== undefined) clearTimeout(timer)
    }
  }, [backend, reviewOpened, reviewVersion])

  const reset = useCallback(() => {
    threadRef.current = []
    setThread([])
    setTab("transcript")
    held.current = null
    setReview(NO_REVIEW_STATE)
    setReviewOpened(false)
    asked.current = 0
  }, [])

  return useMemo(
    () => ({ thread, ask, review, goal, tab, setTab: changeTab, reset }),
    [thread, ask, review, goal, tab, changeTab, reset]
  )
}

/** The last few exchanges, flattened into the alternating roles the worker reads. */
function historyFrom(thread: readonly AskExchange[]): AskMessage[] {
  const messages: AskMessage[] = []
  for (const entry of thread) {
    if (!entry.answer) continue
    messages.push({ role: "learner", text: entry.question })
    messages.push({ role: "coach", text: entry.answer })
  }
  return messages.slice(-ASK_HISTORY_MESSAGES)
}
